---
name: "Gitpod"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      # renovate: datasource=github-releases depName=astral-sh/uv
      UV_VERSION: 0.5.7

    steps:
      - name: Set TERM environment variable
        run: echo "TERM=xterm" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version-file: '.python-version' # Read python version from a file .python-version

      - name: Install dependencies (pip)
        run: make bootstrap --debug

      - run: |
          rm -rf .venv
          pip cache purge

      - run: |
          # Show available shell options
          INSTALL_SCRIPT=$(mktemp)
          curl -LsSf https://astral.sh/uv/install.sh -o "$INSTALL_SCRIPT"
          sh "$INSTALL_SCRIPT" --help
          curl -LsSf "https://astral.sh/uv/${UV_VERSION}/install.sh" -o "$INSTALL_SCRIPT"
          sh "$INSTALL_SCRIPT" -v

      - name: Install dependencies (uv)
        run: make bootstrap --debug

      - name: Run Gitpod tests
        uses: nick-invision/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 # v3
        with:
          max_attempts: 3
          timeout_minutes: 10
          command: make gitpod-tests --debug
